Added custom style for the "Delete" and "Save" buttons from the delete confirmation page.
fabiocaccamo/django-admin-interface pull request #123
Opened 2021-04-01 15:13 UTC by natmil

![cofirmatio-delete](https://user-images.githubusercontent.com/18117559/113315429-93e44280-930d-11eb-922b-9ccb925dbc7e.PNG)

2021-04-01 15:16 UTC, natmil commented
Well, not "Save" button, "Cancel" instead. 😁

2021-04-01 15:16 UTC, fabiocaccamo commented
Could you explain what problem is fixed by this PR please?

2021-04-01 15:21 UTC, natmil commented
> Could you explain what problem is fixed by this PR please?

Of course! The delete confirmation page didn't change the colors that you had configurated in the first place.

![deletesave1](https://user-images.githubusercontent.com/18117559/113316339-81b6d400-930e-11eb-85d1-076f6547da02.PNG)

The cancel button was fine, but not the hover.

![deletesave2](https://user-images.githubusercontent.com/18117559/113316485-af038200-930e-11eb-9d1f-ad01ca691db0.PNG)

![deletesave3](https://user-images.githubusercontent.com/18117559/113316491-b0cd4580-930e-11eb-804d-e098c19dc78a.PNG)

2021-04-01 15:22 UTC, fabiocaccamo commented
@natmil perfect, thank you!

2021-04-01 15:24 UTC, fabiocaccamo requested changes

2021-04-01 15:24 UTC, fabiocaccamo commented on admin_interface/templates/admin_interface/css/admin-interface.css
> +.delete-confirmation form .cancel-link:hover {
Please add always `.admin-interface` body class prefix to all selectors.

2021-04-01 15:24 UTC, fabiocaccamo commented on admin_interface/templates/admin_interface/css/admin-interface.css
> +.delete-confirmation form input[type="submit"] {
Same as above.

2021-04-01 15:24 UTC, fabiocaccamo commented on admin_interface/templates/admin_interface/css/admin-interface.css
> +.delete-confirmation form input[type="submit"]:hover {
Same as above.

2021-04-06 12:31 UTC, fabiocaccamo commented
@natmil could you fix the selector prefix, please?

2021-04-07 13:09 UTC, merged

2021-04-07 15:04 UTC, merwok commented
So this was merged without correcting the selector?

2021-04-07 15:05 UTC, fabiocaccamo commented
@merwok yes, I fixed it [here](https://github.com/fabiocaccamo/django-admin-interface/commit/aec7ede184f03939b8476000d400f1050b367980).