Add support for collapsible fieldsets that start expanded
fabiocaccamo/django-admin-interface pull request #177
Opened 2022-09-27 19:33 UTC by merwok

fixes #173

2022-09-28 08:08 UTC, fabiocaccamo requested changes

2022-09-28 08:08 UTC, fabiocaccamo commented on README.md
> +- Collapsible fieldsets can have their initial state be expanded
Maybe adding here a link to the relative admin section would be useful.

2022-09-28 08:08 UTC, fabiocaccamo commented on README.md
> +            "classes": ("collapse", "initial-show"),
I think that a class name like `collapse-expanded` or just `expanded` would be more intuitive and easier to remember.

2022-09-28 19:08 UTC, merwok commented
Because there is a separate ticket about remembering the collapsed state, and I have to spend time on the list filter changes for now, I am marking this ready for review on its own!

2022-09-29 07:36 UTC, fabiocaccamo approved these changes
Thank you very much for this PR!

2022-09-29 07:37 UTC, merged